### ISSUE TITLE
Unnamed specs are incorrectly reporting invalid

### ISSUE THREAD

**Issue by briansfrank** [Novo-Int/xeto-vscode-extension#39]
Nested unnamed specs are incorrectly reporting invalid syntax with the error "Expecting end of proto..."

Here is an example of legal Xeto:

      ButtonTest : BorderBox {
        insets: 10
        VBox {
          HBox {
            gap: 10
            Button {
              Text { text: "Button" }
              onAction: Axon """(e) => echo("Pressed: " + e)"""
            }
            Button {
              Text { text: "Disabled" },
              traits: { disabled }
            }
          }
        }
      }

**Comment by hades2510** [comment]
should be fixed in `0.1.25`

**Comment by rracariu** [comment]
verified with 0.1.26
