### ISSUE TITLE
In the outline view, show the type name not the indexes.

### ISSUE THREAD

**Issue by rracariu** [Novo-Int/xeto-vscode-extension#45]
When you have a sequence of types, instead of showing the index of each type used, show the type name in the outline view:

<img width="308" alt="image" src="https://github.com/Novo-Int/xeto-vscode-extension/assets/14125806/1c999a7e-2a0a-4bf0-aec2-f670c562ac28">

<img width="273" alt="image" src="https://github.com/Novo-Int/xeto-vscode-extension/assets/14125806/06bf7d07-2c7c-4a48-bf73-4e6574f963b8">

**Comment by hades2510** [comment]
this should be fixed in 0.1.28

**Comment by rracariu** [comment]
Tested with 0.1.28
