### ISSUE TITLE
Name resolution should mark conflicts with dependency types

### ISSUE THREAD

**Issue by rracariu** [Novo-Int/xeto-vscode-extension#46]
For a  library that uses `ph` lib as a dependency, this would be market as an error:

```
Equip: Dict {}
```

Here `Equip` would conflict with the `Equip` spec from the `ph` lib

**Comment by hades2510** [comment]
Is that really a problem ?

I think the issues arrises when you are trying to reference `Equip` and there are multiple libs to resolve this from.

So trying to something like this 

```
Foo: {
 slot: Equip
}
```

Should result in an error. 
In other words declaring an alias wouldn't be an error, but referencing a type that has name ambiguity would be an error.
I'm not sure if fully qualifying the reference should be an error or not. Something like this

```
Baz: {
 slot1: ph::Equip
 slot2: fooLib::Equip
}
```

**Comment by rracariu** [comment]
I can't replicate this anymore, there was an error in the xeto compiler while demoing at the show and I added this at that time.
